# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20170715_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
